<?php

namespace App\Filament\Resources\TeachingMaterialResource\Pages;

use App\Filament\Resources\TeachingMaterialResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditTeachingMaterial extends EditRecord
{
    protected static string $resource = TeachingMaterialResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\ViewAction::make(),
            Actions\DeleteAction::make(),
        ];
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        if($data['unlimited_view'])
            $data['maximum_views'] = 0;

        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }
}
